name: Create Blender ZIP

on:
  push:
    paths:
      - "condor_buildings/**"
      - "README.md"
      - "LICENSE"

permissions:
  contents: write

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get addon version
        id: version
        run: |
          VERSION=$(grep -o '"version": ([0-9, ]*)' condor_buildings/__init__.py | grep -o '[0-9, ]*' | tr -d ' ' | tr ',' '.')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Prepare Blender ZIP package
        run: |
          cp README.md condor_buildings/
          cp LICENSE condor_buildings/
          zip -r condor_buildings.zip condor_buildings

      - name: Create Release and upload ZIP
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: Condor Buildings v${{ steps.version.outputs.version }}
          files: condor_buildings.zip
